# GitHub Pages configuration

# Use the DevPortfolio theme by Ryan Fitzgerald
remote_theme: RyanFitzgerald/devportfolio

# Include custom CSS
sass:
  load_paths:
    - _sass
    - assets/css

# Site settings
lang: en-US
title: Ravindra Naik - Cloud Architect & GenAI Evangelist
description: Cloud Architect and GenAI Evangelist with 12+ years of expertise in scalable systems, AI automation, and energy intelligence platforms
url: "https://naik899.github.io"
baseurl: ""

# SEO settings
google_analytics: # Add your GA tracking ID here if needed
google_analytics_anonymize_ip: true

# Author information
author:
  name: Ravindra Naik
  email: naik899@gmail.com
  location: Bengaluru, Karnataka, India
  bio: Cloud Architect & GenAI Evangelist | Energy Intelligence Platform
  avatar: assets/images/ravi.jpeg
  social:
    linkedin: naik899
    github: naik899
    twitter: naik899

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /#about
  - title: Experience
    url: /#experience
  - title: Projects
    url: /#projects
  - title: Blog
    url: /blog/
  - title: Categories
    url: /categories/
  - title: Contact
    url: /#contact

# Blog settings
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge

