# GitHub Pages configuration

# Use the DevPortfolio theme by Ryan Fitzgerald
remote_theme: RyanFitzgerald/devportfolio

# Site settings
lang: en-US
title: Ravindra Naik
description: Portfolio site hosted on GitHub Pages

